name: install
description: Install the package and dependencies
inputs:
  python-version:
    required: true
    description: 'The python version to use'
  os:
    required: true
    description: 'The OS to use'
  install-gui:
    required: false
    description: 'Whether to install the GUI dependencies'
    default: true
  pipfile-version:
    required: false
    description: 'The pipfile version to use. Can be min, max, latest'
    default: 'min'
outputs:
  to-update:
    description: "True if the dependencies can be updated"
    value: ${{ steps.install-dependencies.outputs.diff != '' }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      shell: bash

    - name: Install minium supported dependencies
      if: inputs.pipenv-version == 'min'
      run: pipenv install --dev --python=${{ inputs.python-version }}
      shell: bash

    - name: Install unperbound supported dependencies
      if: inputs.pipenv-version == 'max'
      run: |
        # Override the current Pipfile with the Pipfile containing the max versions
        rm Pipfile
        mv Pipfile.sup Pipfile
        pipenv install --dev --python=${{ inputs.python-version }}
      shell: bash

    # - name: Check if the latest version supported is up to date.
    #   id: install-dependencies
    #   if: inputs.pipenv-version == 'latest'
    #   continue-on-error: true
    #   run: |
    #     # Generate the Pipfile with the latest version
    #     pip install -r tools/packages/requirements.txt
    #     python tools/packages/manager.py pipfile tools/packages/taipy-core/setup.requirements.txt tools/packages/taipy/setup.requirements.txt tools/packages/taipy-gui/setup.requirements.txt tools/packages/taipy-config/setup.requirements.txt tools/packages/taipy-rest/setup.requirements.txt Pipfile
    #     # If Pipfile and Pipfile.sup are different, put something in the GitHub convertation
    #     {
    #       echo 'diff<<EOF'
    #       echo `diff Pipfile Pipfile.sup | tail -n +1`
    #       echo EOF
    #     } >> "$GITHUB_OUTPUT"
    #   shell: bash

    # - name: Comment PR
    #   if: inputs.can-comment-pr && steps.install-dependencies.outputs.diff != ''
    #   uses: thollander/actions-comment-pull-request@v2
    #   with:
    #     message: |
    #       Diff deteteced ! Please update the Pipfile.sup file with the following diff:
    #       ```
    #       ${{ steps.install-dependencies.outputs.diff }}
    #       ```

    # - name: Install Dependencies
    #   if: inputs.pipenv-version == 'latest' && steps.install-dependencies.outputs.exit_code == 0
    #   run: pipenv install --dev --python=${{ inputs.python-version }}
    #   shell: bash

    - name: Setup LibMagic (MacOS)
      if: inputs.os == 'macos-latest'
      run: brew install libmagic
      shell: bash

    - uses: actions/setup-node@v4
      if: inputs.install-gui
      with:
        node-version: 20

    - name: Frontend Bundle Build
      if: inputs.install-gui
      run: pipenv run python tools/frontend/bundle_build.py
      shell: bash

    - name: Install Playwright
      if: inputs.install-gui
      run: pipenv run playwright install chromium --with-deps
      shell: bash
