name: Prefix (baseURL) Test
runs:
  using: "composite"
  defaults:
    run:
      shell: bash
  steps:
    - name: Build the Docker image
      working-directory: ./tools/gui/docker/nginx-prefix
      run: docker build . --file Dockerfile --tag taipy-nginx-proxy
    - name: run nginx reverse proxy docker container
      run: docker run -d -p 4000:4000 taipy-nginx-proxy
    - name: run pytest with prefix configuration
      run: pipenv run pytest -m "teste2e" tests/gui/e2e --e2e-base-url="/prefix/" --e2e-port="4000"
