name: Overall Test Workflow

on:
  push:
    branches: [ develop, dev/*, release/* ]
  pull_request:
    branches: [ develop, dev/*, release/* ]

jobs:
  partial-tests:
    uses: ./.github/workflows/partial-tests.yml

  overall-tests:
    needs: [partial-tests]
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
        pipenv-version: ['min', 'max', 'latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Dependencies
        if: matrix.pipenv-version == 'min'
        run: pipenv install --dev --python=${{ matrix.python-version }}

      - name: Install Dependencies
        if: matrix.pipenv-version == 'max'
        run: |
          # Override the current Pipfile with the Pipfile containing the max versions
          mv Pipfile.sup Pipfile
          pipenv install --dev --python=${{ matrix.python-version }}

      - name: Install Dependencies
        id: install-dependencies
        if: matrix.pipenv-version == 'latest'
        continue-on-error: true
        run: |
          # Generate the Pipfile with the latest version
          pip install -r tools/packages/requirements.txt
          python tools/packages/manager.py pipfile tools/packages/taipy-core/setup.requirements.txt tools/packages/taipy/setup.requirements.txt tools/packages/taipy-gui/setup.requirements.txt tools/packages/taipy-config/setup.requirements.txt tools/packages/taipy-rest/setup.requirements.txt Pipfile
      
      - name: Install Dependencies
        if: matrix.pipenv-version == 'latest' && steps.install-dependencies.outputs.status == 'success'
        run: pipenv install --dev --python=${{ matrix.python-version }}

      - name: Setup LibMagic (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install libmagic

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend Bundle Build
        run: pipenv run python tools/frontend/bundle_build.py

      - name: Install Playwright
        run: pipenv run playwright install chromium --with-deps

      - name: Pytest
        run: pipenv run pytest -m "not orchestrator_dispatcher and not standalone" --cov=taipy --cov-append --cov-report="xml:overall-coverage.xml" --cov-report term-missing tests

      - name: Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11' && matrix.pipenv-version == 'min'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./overall-coverage.xml
          title: Taipy Overall Coverage Report

  submit_tests:
    needs: [partial-tests]
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Dependencies
        run: pipenv install --dev --python=${{ matrix.python-version }}

      - name: Setup LibMagic (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install libmagic

      - name: Pytest Core orchestrator_dispatcher
        run: pipenv run pytest -m "orchestrator_dispatcher" tests/core

  standalone_tests:
    needs: [partial-tests]
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Dependencies
        run: pipenv install --dev --python=${{ matrix.python-version }}

      - name: Setup LibMagic (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install libmagic

      - name: Pytest Core standalone
        run: pipenv run pytest -m "standalone" tests/core
