name: Publish pre-release to github

on:
  workflow_dispatch

jobs:
  publish:
    timeout-minutes: 20
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ensure package version is properly set
        id: current_version
        run: |
              echo """
              import json, sys, os
              with open(f\"src{os.sep}taipy{os.sep}version.json\") as version_file:
                  version_o = json.load(version_file)
              version = f'{version_o.get(\"major\")}.{version_o.get(\"minor\")}.{version_o.get(\"patch\")}'
              if vext := version_o.get(\"ext\"):
                  version = f'{version}.{vext}'
              print(f'VERSION={version}')
              """ > /tmp/check1.py
              python /tmp/check1.py >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install build
            pip install git+https://git@github.com/Avaiga/taipy-gui.git@develop

      - name: Build package
        run: python setup.py build_py && python -m build

      - name: Create/update release and tag
        run: |
            gh release delete dev-${{ steps.current_version.outputs.VERSION }} -y || true
            gh release create dev-${{ steps.current_version.outputs.VERSION }} ./dist/taipy-${{ steps.current_version.outputs.VERSION }}.tar.gz --draft --prerelease --notes "Release Draft ${{ steps.current_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
